"""
Celery task — J+7 follow-up emails.

Finds qualified prospects (prospect_email set, no visit booked, conversation
created 7+ days ago) and sends a personalized follow-up email generated by GPT.

A sentinel Message(role="system", content="FOLLOWUP_SENT:…") is written to the
conversation so the prospect is never emailed twice.
"""
from __future__ import annotations

import logging
from datetime import datetime, timedelta, timezone

from celery import shared_task
from openai import OpenAI

from app.config import settings
from app.database.connection import SessionLocal
from app.database.models import Conversation, Message

logger = logging.getLogger(__name__)

_FOLLOWUP_SYSTEM = (
    "Tu es l'assistant de l'agence immobilière ImmoPlus. "
    "Rédige un email de relance chaleureux et professionnel (3-4 phrases maximum) "
    "pour un prospect qui avait recherché un bien il y a une semaine sans prendre rendez-vous. "
    "L'email doit proposer d'organiser une visite et rappeler la disponibilité de l'équipe. "
    "Commence directement par le corps du message — pas de sujet, pas de formule 'Objet :'."
)


def _build_criteria_text(criteria: dict) -> str:
    if not criteria:
        return "bien immobilier à Lyon"
    parts = []
    if criteria.get("type"):
        parts.append(criteria["type"])
    if criteria.get("city"):
        parts.append(f"à {criteria['city']}")
    if criteria.get("max_price"):
        parts.append(f"budget {int(criteria['max_price']):,} €".replace(",", " "))
    if criteria.get("min_surface"):
        parts.append(f"{criteria['min_surface']} m² min")
    if criteria.get("min_rooms"):
        parts.append(f"{criteria['min_rooms']} pièces min")
    return ", ".join(parts) if parts else "bien immobilier à Lyon"


def _build_html(name: str, body: str) -> str:
    body_html = body.replace("\n", "<br>")
    return f"""
    <div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto">
      <div style="background:#1a2b4a;padding:20px 30px">
        <h1 style="color:#fff;margin:0;font-size:22px;font-weight:700">ImmoPlus</h1>
        <p style="color:#93c5fd;margin:4px 0 0;font-size:13px">Votre agence immobilière à Lyon</p>
      </div>
      <div style="padding:30px;background:#fff;border:1px solid #e2e8f0">
        <p style="margin:0 0 16px">Bonjour {name},</p>
        <p style="margin:0 0 16px;line-height:1.6">{body_html}</p>
        <div style="margin:24px 0">
          <a href="https://immoplus.fr" style="background:#1d4ed8;color:#fff;padding:12px 24px;border-radius:6px;text-decoration:none;font-weight:600;display:inline-block">
            Prendre rendez-vous
          </a>
        </div>
        <p style="color:#64748b;font-size:13px;margin:0">L'équipe ImmoPlus — 04 72 00 00 00</p>
      </div>
    </div>"""


@shared_task(name="app.tasks.followup_tasks.send_followup_drafts", bind=True, max_retries=2)
def send_followup_drafts(self):
    """Send J+7 follow-up emails to qualified prospects who haven't booked a visit."""
    from app.services.email_service import send_email

    db = SessionLocal()
    client = OpenAI(api_key=settings.OPENAI_API_KEY)
    sent = 0
    skipped = 0
    errors = 0

    try:
        cutoff = datetime.now(timezone.utc) - timedelta(days=7)

        convs = (
            db.query(Conversation)
            .filter(
                Conversation.prospect_email.isnot(None),
                Conversation.status != "visit_booked",
                Conversation.created_at < cutoff,
            )
            .all()
        )

        logger.info("Followup task: %d candidate conversations", len(convs))

        for conv in convs:
            # Skip if already sent
            already = (
                db.query(Message)
                .filter(
                    Message.conversation_id == conv.id,
                    Message.role == "system",
                    Message.content.like("FOLLOWUP_SENT:%"),
                )
                .first()
            )
            if already:
                skipped += 1
                continue

            # Generate personalized email body
            name = conv.prospect_name or "cher(e) prospect"
            criteria_text = _build_criteria_text(conv.search_criteria or {})

            try:
                resp = client.chat.completions.create(
                    model=settings.OPENAI_MODEL_MINI,
                    messages=[
                        {"role": "system", "content": _FOLLOWUP_SYSTEM},
                        {"role": "user", "content": (
                            f"Prénom du prospect : {name}\n"
                            f"Sa recherche : {criteria_text}\n"
                            "Rédige le corps de l'email."
                        )},
                    ],
                    temperature=0.7,
                    max_tokens=300,
                )
                body = resp.choices[0].message.content.strip()
            except Exception as exc:
                logger.error("GPT followup generation failed for conv %s: %s", conv.id, exc)
                errors += 1
                continue

            # Send email
            subject = f"ImmoPlus — {name}, avez-vous trouvé votre bien idéal ?"
            try:
                send_email(conv.prospect_email, subject, _build_html(name, body))
            except Exception as exc:
                logger.error("Followup email send failed for %s: %s", conv.prospect_email, exc)
                errors += 1
                continue

            # Mark as sent (sentinel message — prevents duplicate sends)
            db.add(Message(
                conversation_id=conv.id,
                role="system",
                content=f"FOLLOWUP_SENT:{datetime.now(timezone.utc).isoformat()}",
            ))
            db.commit()
            sent += 1
            logger.info("Followup J+7 sent → %s (conv %s)", conv.prospect_email, conv.id)

    except Exception as exc:
        logger.error("Followup task crashed: %s", exc, exc_info=True)
        raise self.retry(exc=exc, countdown=600)
    finally:
        db.close()

    logger.info("Followup task done: %d sent, %d skipped, %d errors", sent, skipped, errors)
    return {"sent": sent, "skipped": skipped, "errors": errors}
